ver 0.9.0
AlexBragin1/go-db-sql-final pull request #1
Opened 2024-01-23 20:25 UTC by AlexBragin1

2024-01-23 21:04 UTC, robotomize requested changes
Отличная работа, но есть ряд моментов которые нужно поправить

2024-01-23 21:04 UTC, robotomize commented on parcel/parcel.go
> +	_, err := s.db.Exec("DELETE FROM parcel WHERE  number = :number", sql.Named("number", number))
Или можете вынести эту логику в сервис скажем, тогда в нем будет три операции, получить посылку, проверить статус удалить посылку. Аналогично и для адреса

2024-01-23 21:04 UTC, robotomize commented on parcel/parcel_test.go
> +	assert.Equal(t, ParcelStatusSent, pGet.Status)
Не могу понять откуда взялся статус Sent если по умолчанию у нас регистеред, а мы его нигде не меняли

2024-01-25 20:03 UTC, AlexBragin1 commented on parcel/parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET address = :address, number = :number WHERE status = registered",
здесь еть проверка, что статус registered

2024-01-25 20:24 UTC, AlexBragin1 commented on parcel/parcel.go
> +	}
сделал

2024-01-25 20:24 UTC, AlexBragin1 commented on parcel/parcel.go
> +		fmt.Println(err)
сделал

2024-01-25 20:25 UTC, robotomize commented on parcel/parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET address = :address, number = :number WHERE status = registered",
Вы правы, глаз замылился не заметил. 1000 извинений. Я думаю, что жто валидный кейс и тут и в Delete
Можно конечно отдать пользователю ошибку, почему он не может обновить адрес, или удалить запись. Но по большому счету и так и так я считаю будет правильно

2024-01-25 20:25 UTC, AlexBragin1 commented on parcel/parcel.go
> +	_, err := s.db.Exec("DELETE FROM parcel WHERE  number = :number", sql.Named("number", number))
добавил where status  = registered , можно через like

2024-01-25 20:26 UTC, AlexBragin1 commented on parcel/parcel.go
> +	rows, err := s.db.Query("SELECT number,client,status,address,createdAt FROM parcel WHERE number = :number", sql.Named("number", number))
сделал

2024-01-25 20:26 UTC, AlexBragin1 commented on parcel/parcel_test.go
> +	assert.Equal(t, parcel, pGet)
parcel.number

2024-01-25 20:26 UTC, AlexBragin1 commented on parcel/parcel_test.go
> +	assert.Equal(t, ParcelStatusSent, pGet.Status)
сделал

2024-01-26 06:43 UTC, robotomize approved these changes
Отлично, круто что исправили ошибки. Обратите внимание на коммент с Delete/SetAdress

2024-01-26 06:43 UTC, robotomize commented on parcel/parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET address = :address, number = :number WHERE status = registered",
Да, единственное сделайте проверку статуса через параметр также как и number и используйте константу статуса `ParcelStatusRegistered`

2024-01-26 06:43 UTC, robotomize commented on parcel/parcel.go
> +	_, err := s.db.Exec("DELETE FROM parcel WHERE  number = :number WHERE status = registered", sql.Named("number", number))
Да, единственное сделайте проверку статуса через параметр также как и number и используйте константу статуса `ParcelStatusRegistered`

2024-01-26 06:43 UTC, robotomize commented on parcel/parcel_test.go
> +		require.NoError(t, err)
Я думаю тут можно просто вызывать t.Fatal(err) если коннекшен не смогли открыть

2024-01-27 12:32 UTC, merged